### ISSUE TITLE
Tooltip leaves page

### ISSUE THREAD

**Issue by jaimefps** [cypress-io/cypress-design#257]
![Screen Shot 2023-06-12 at 8 30 44 PM](https://github.com/cypress-io/cypress-design/assets/19941627/d891ecb4-09d8-438d-a225-689ba3e51f36)

Issue: 
When the tooltip is close to the side of the screen, if leaves bleeds out of the page and cuts the content.

Expected behavior:
The tooltip automatically adjusts to keep all content within view.

**Comment by elevatebart** [comment]
It will be a bit of work to detect collision, at open and at scroll/resize. 
I think the floating-dom library we are using can do this.

Let me check it out.
