### ISSUE TITLE
fillColor is not respected when passed in curly braces IconStatusRunningOutline

### ISSUE THREAD

**Issue by mabela416** [cypress-io/cypress-design#262]
In `IconStatusRunningOutline` and possibly other icons, if you pass the `fillColor `inside curly braces, it doesn't respect it. This includes passing it as a variable as well

```
      <IconStatusRunningOutline
        fillColor={'gray-800'}
        size="16"
      />
```
or
```
      const gray800 = 'gray-800';
      <IconStatusRunningOutline
        fillColor={gray800}
        size="16"
      />
```

Passing `fillColor` only works when passed as a string
```
      <IconStatusRunningOutline
        fillColor='gray-800'
        size="16"
      />
```

**Comment by elevatebart** [comment]
I will see what I can do.
The solution might very well be to document the edge case on the design system website.
