### ISSUE TITLE
bug: Tabs component breaks on resize

### ISSUE THREAD

**Issue by jaimefps** [cypress-io/cypress-design#307]
Demo: https://www.loom.com/share/d7fc1b771ecd474883064ace017a2e17

**Comment by jaimefps** [comment]
@elevatebart This is impacting the TestReplay experience, and we are hoping to go GA on Tuesday; is there any chance you can look into this before then so we can hopefully include a fix before release?

**Comment by elevatebart** [comment]
I will do my best... It would be one of those issues where you send me the testReplay and it's an easy fix.

Now I need to create my repro myself :D
