### ISSUE TITLE
Console warning caused by tooltip

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress-design#443]
The tooltip from the design system causes this warning in the console:
![Screenshot 2024-06-11 at 12 54 25 PM](https://github.com/cypress-io/cypress-design/assets/26726429/b5a3c87f-d84d-4c9a-9c0e-a94633cf0ad9)

[See Loom](https://www.loom.com/share/58eeabb330c145fe826ffa97e527e711)

Version: `"@cypress-design/react-tooltip "0.10.1"`

(I accidentally previously wrote `"@cypress/react-tooltip": "0.5.4",`)

**Comment by elevatebart** [comment]
Hello @rachelruderman 

The version the Cloud is using is quite old and has an issue.
Have you tried updating the package?

If not I will try and report back.

Bart

**Comment by elevatebart** [comment]
I missed it ... this is not the right repo https://github.com/cypress-io/react-tooltip

**Comment by rachelruderman** [comment]
Whoopsie!!! Thank you so much!! That went right over my head 😅

**Comment by rachelruderman** [comment]
Reopening this; I accidentally put the wrong version in the package.json. This is using:

`import Tooltip from '@cypress-design/react-tooltip'` version `version "0.10.1"`
